### ISSUE TITLE
Also remove gclid

### ISSUE THREAD

**Issue by thomasrussellmurphy** [sbedell/web-extensions#1]
Could the param remover extension be updated to also remove `gclid` parameters?

**Comment by sbedell** [comment]
I just updated this add-on to remove gclid. Version 1.1, should be available via regular updates now. Sorry that this took so long!

**Comment by sbedell** [comment]
Closing it, update released on Mozilla Add-ons (AMO).

**Comment by MatMarrr** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mdegraw, @lapitskiy, @asaglimbeni, @mstarnes, @wanwenli, @yildizberkay, @ayuthmang, @sylvat, @dylanzan, @Wally-7up, @jeradf, @fengzhenrong, @catalin-sandru, @PyPatel, @Sean-Ker, @wytxty, @khoand0000, @moonorblue, @pgkk, @Tolkoton, @wufeiafei, @nameisjh, @aplucas, @Toxirbek9222, @kathgironpe, @carlos846, @mostafalarki1368mos, @arontang, @wangzhiqiang, @Shellnco, @xd502djj, @lightblack2011, @gregl83, @leobooth, @kennyledet, @raphaelm22, @joshlevi, @profile1p, @unitwk, @GeekWorkCode, @sqwu, @JiuZhuYou, @RaceToohey, @popvip, @Ruthjay, @Twan1409, @johninn, @JimAmuro, @justmayankno13, @yhgwyrghleoyey, @jovianlin, @jadireddi, @galfred384, @ordomalleus, @ogz00, @tangivis, @farhan711, @sg552, @chenzeZzz, @satoshissss, @vyorkin, @zicroc, @JacobAlvarezSE, @cimpapps, @nick-tang, @matebestek, @dmytrobieliaiev, @sdl9i2, @Mikolaj-Agalarov, @poupkine, @qujunde, @cinderspire, @123456789-bb, @DimaJoyti, @khlylkhatwnltfy, @mutalisk999, @trihtm, @DaReal6God, @thomasxnguy, @Abnerfang, @kosyachniy, @davy-guilherme, @Hairdmin, @xuantinfx, @yangjietadie, @mahmoud-eskandari, @ryot, @siwilizhao, @yimings2072, @nscarlson, @Giannipx, @Piou-piou, @RomaniukVadim, @latifuluman, @krishna-praveen, @bitforce, @0xByteLeon, @Stef3478, @antx-code

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
bleib1dj, @cvaldrighi, @syuhair, @Littlebigdondon, @EngAbdalrhman, @xjose97x, @opt9, @galchenkov, @Manoj-Paramsetti, @hanachan1026, @Jordinaa, @Debu976116, @ychyss, @edrygka, @johndacost, @aleksraiden, @beblueblue, @pea06, @m4292007, @xeusteerapat, @naveennoel, @BlockchainWatchDog, @deifh1118, @MiranKrd, @evanxuw, @CarolineGaoN, @mlg87, @Danialo789, @alexkubica, @owlinstack, @Sh1d0w, @CharlesHilgeman, @sriharshakappala, @danilevy1212, @kevincharm, @jsimmons1980, @emmanuelkuyisan, @feng92f, @ashishawasthi, @joanjpx, @sdhou, @chozeur, @andreaselia, @zenithlel, @johnforgit, @Caiwen612, @cheebo, @lincunjun, @toneliu, @jagarinartwerdnajoc, @shahabkamali, @leavenotrace, @tengkuhanis, @savi2w, @marcoonroad, @askanium, @tiramisugg, @MKFMIKU, @uniyalabhishek, @prateeksawhney97, @berryjam, @tim-hash, @jymartineau, @wilsongumba, @mary-lilypad, @safa-eristi, @CryptYlliON, @rerange, @kevinchensr, @vaibhav-jain, @mathlet0x, @omerta83, @ZhiShiMao, @rahimsghir, @sophiacodes, @axiaxx, @thealidev, @SteveXCIV, @didierkrux, @bjarnard, @fridarode, @sacredwx, @cavaon-wayne, @droxey, @01luismeza, @ctkqiang, @2246040006, @yijiehuanshen, @KeanuPang, @stasb, @lazzarello, @dogagcmnr, @FAVE01, @ztwangjing, @lwtsn, @feralconsultant, @esneko, @shunkakinoki, @freedomhero

**Comment by byungster** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
anc95, @Hokore-Dev, @exqlnet, @BenNormous, @davidchai, @charlenopires, @CleverOscar, @profcase, @Fahid-Shaheen, @anthonypreza, @snatvb, @bondcoder97, @blazingsiyan, @garnathere, @thorstenhirsch, @abhiraj-kale, @JackMallon, @takahiro-prog, @RCiesielczuk, @ATreep, @agarwalchaitanya, @johncrisostomo, @Saberhabeelshohdy, @lovincyrus, @valtab, @velihdzen, @patrick-michelberger, @NhatTan2803, @Matrixbirds, @D-ping, @guiguan, @alexandrule, @feiw24, @roadmanfong, @michaelkirschbaum, @vpodolyan, @sixvxsh, @jibolaoseni, @lilhorse, @CQBinh, @Djenkaa, @samuelzuuka, @dlgchg, @vikasr111, @nuel-ikwuoma, @GaloisField2718, @angeliedu, @yuhatown, @zhangli344236745, @Jasonchang6435china-xuhappy, @PaulRBerg, @gabyden, @mesuutt, @z3r086, @blackhblee, @greatbsky, @milne-dev, @DougAnderson444, @a2012s, @yuanshichao1988, @sgeniusd, @BernhardWenzel, @XxwizxX, @101t, @KambizAsadzadeh, @MRLoyalMafiaa247, @rennokki, @dannysofftie, @toppyc4, @xgoo, @afxal, @davidhperry, @nattaphat, @krebernisak, @samirettali, @Drblessing, @zaferonan, @MajorTom404, @lggg123, @racranjan, @ShawkyHanna, @elirocha2014, @andrefbcorreia, @DonCaton, @maksaiduhka, @srsgores, @mortezakarimi, @0x1ea, @tatiesmars, @WatchTower001110, @scalybur, @rudyZanotti, @rae-ralston, @RFARREY, @dzincolorado, @omysurya, @WisemanLim, @williammoraes, @agdolla
